name: Pixel Stream
favicon: null
layout_spectrum: 0.3603402639273554
typography_spectrum: 0.03675925522111356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.853512751404196
  lightness: 0.6217175559140742
  saturation: 0.5597635805606842
  rhythmicContrast: 0.5251682896632701
purpose: []
